Repository tomiban/Hotel-Management-System-TP, pull requests merged in 2024-09, with the labels that each got.

#35 Añadir habitacion
  src/Domain/Entities/Habitacion/Habitacion.cs
  src/Domain/Entities/Habitacion/IHabitacion.cs
  src/Infraestructure/DataAccess/Repositories/HabitacionRepository.cs
  src/Presentation/Presenters/AdminPresenter.cs
  src/Presentation/Presenters/CrearEditarHabitacionPresenter.cs
  src/Presentation/Presenters/ICrearEditarHabitacionPresenter.cs
  src/Presentation/Presenters/ILoginPresenter.cs
  src/Presentation/Presenters/LoginPresenter.cs
  src/Presentation/Presenters/RegisterPresenter.cs
  src/Presentation/Program.cs
  src/Presentation/Views/AdminView.cs
  src/Presentation/Views/AdminView.resx
  src/Presentation/Views/CrearEditarHabitacionView.Designer.cs
  src/Presentation/Views/CrearEditarHabitacionView.cs
  src/Presentation/Views/IAdminView.cs
  src/Presentation/Views/ICrearEditarHabitacionView.cs
  src/Presentation/Views/RegisterView.cs
  src/Services/Services/HabitacionServices.cs
  src/Services/Services/IHabitacionServices.cs
Labels: enhancement

#41 Remueve async de los nombres de los metodos
  src/Domain/Interfaces/IGenericRepository.cs
  src/Infraestructure/DataAccess/Repositories/HabitacionRepository.cs
  src/Infraestructure/DataAccess/Repositories/ReservaRepository.cs
  src/Infraestructure/DataAccess/Repositories/UsuarioRepository.cs
  src/Services/Services/AuthService.cs
  src/Services/Services/HabitacionServices.cs
  src/Services/Services/UsuarioService.cs
Labels: fix

#42 Listar habitaciones en la la vista de huesped
  Assets
  GestionHotelWF.sln
  src/Domain/Entities/Factura/Factura.cs
  src/Domain/Entities/Habitacion/Habitacion.cs
  src/Domain/Entities/Reserva/IReserva.cs
  src/Domain/Entities/Reserva/Reserva.cs
  src/Infraestructure/DataAccess/Repositories/HabitacionRepository.cs
  src/Infraestructure/DataAccess/Repositories/ReservaRepository.cs
  src/Infraestructure/DataAccess/Repositories/UsuarioRepository.cs
  src/Presentation/Assets/account_circle.png
  src/Presentation/Assets/add.png
  src/Presentation/Assets/admin_panel.png
  src/Presentation/Assets/apartment.png
  src/Presentation/Assets/bed.png
  src/Presentation/Assets/bedroom_parent.png
  src/Presentation/Assets/book.png
  src/Presentation/Assets/bookmark_check.png
  src/Presentation/Assets/dashboard.png
  src/Presentation/Assets/door.png
  src/Presentation/Assets/facturacion.png
  src/Presentation/Assets/group.png
  src/Presentation/Assets/logout.png
  src/Presentation/Assets/money.png
  src/Presentation/Assets/person_search.png
  src/Presentation/Components/HabitacionCard.cs
  src/Presentation/Components/HabitacionCardContainer.cs
  src/Presentation/Data/usuarios.bin
  src/Presentation/PresentationLayer.csproj
  src/Presentation/Presenters/GuestPresenter.cs
  src/Presentation/Program.cs
  src/Presentation/Views/AdminView.Designer.cs
  src/Presentation/Views/AdminView.cs
  src/Presentation/Views/AdminView.resx
  src/Presentation/Views/GuestView.Designer.cs
  src/Presentation/Views/GuestView.cs
  src/Presentation/Views/GuestView.resx
  src/Presentation/Views/IGuestView.cs
  src/Presentation/Views/RegisterView.cs
  src/Services/Services/AuthService.cs
  src/Services/Services/IAuthService.cs
  src/Services/Services/IReservaService.cs
  src/Services/Services/ReservaService.cs
Labels: enhancement

#44 Mejora funcionalidad botón "Eliminar"
  src/Presentation/Presenters/AdminPresenter.cs
  src/Presentation/Presenters/CrearEditarHabitacionPresenter.cs
  src/Presentation/Views/AdminView.cs
  src/Presentation/Views/CrearEditarHabitacionView.cs
  src/Presentation/Views/IAdminView.cs
  src/Presentation/Views/ICrearEditarHabitacionView.cs
Labels: style

#59 Funcionalidad para añadir reservas sobre una habitacion
  src/Domain/Entities/Factura/Factura.cs
  src/Domain/Entities/Factura/IFactura.cs
  src/Domain/Entities/Reserva/Reserva.cs
  src/Domain/Interfaces/IReservaRepository.cs
  src/Infraestructure/DataAccess/Repositories/ReservaRepository.cs
  src/Presentation/Presenters/GuestPresenter.cs
  src/Presentation/Views/GuestView.cs
  src/Services/Services/IReservaService.cs
  src/Services/Services/ReservaService.cs
Labels: enhancement

#60 Implementacion de patron factory para crear las cards de las habitaciones
  src/Domain/Entities/Factura/Factura.cs
  src/Domain/Entities/Factura/IFactura.cs
  src/Domain/Interfaces/IReservaRepository.cs
  src/Infraestructure/DataAccess/Repositories/ReservaRepository.cs
  src/Presentation/Components/HabitacionCardContainer.cs
  src/Presentation/Data/usuarios.bin
  src/Presentation/Factories/HabitacionCardFactory.cs
  src/Presentation/Presenters/GuestPresenter.cs
  src/Presentation/Views/GuestView.Designer.cs
  src/Presentation/Views/GuestView.cs
  src/Presentation/Views/GuestView.resx
  src/Presentation/Views/IGuestView.cs
  src/Services/Services/ReservaService.cs
Labels: enhancement

#65 Funcionalidad para editar reserva y cancelar reservas activas
  src/Infraestructure/DataAccess/Repositories/ReservaRepository.cs
  src/Presentation/Helpers/EventHelper.cs
  src/Presentation/Presenters/DetallesReservaPresenter.cs
  src/Presentation/Presenters/GuestPresenter.cs
  src/Presentation/Presenters/IDetallesReservaPresenter.cs
  src/Presentation/Presenters/LoginPresenter.cs
  src/Presentation/Program.cs
  src/Presentation/Views/AdminView.resx
  src/Presentation/Views/CrearEditarHabitacionView.cs
  src/Presentation/Views/DetallesReservaView.Designer.cs
  src/Presentation/Views/DetallesReservaView.cs
  src/Presentation/Views/DetallesReservaView.resx
  src/Presentation/Views/GuestView.cs
  src/Presentation/Views/IDetallesReservaView.cs
  src/Presentation/Views/IGuestView.cs
  src/Presentation/Views/RegisterView.cs
  src/Services/Services/HabitacionServices.cs
  src/Services/Services/IReservaService.cs
  src/Services/Services/ReservaService.cs
Labels: enhancement

#66 Nueva funcionalidad para filtrar habitaciones disponibles para reservar
  src/Domain/Entities/Habitacion/Habitacion.cs
  src/Presentation/Components/HabitacionCard.cs
  src/Presentation/Components/HabitacionCardContainer.cs
  src/Presentation/Events/FiltroFechaEventArgs.cs
  src/Presentation/Events/HabitacionEventArgs.cs
  src/Presentation/Factories/HabitacionCardFactory.cs
  src/Presentation/Presenters/DetallesReservaPresenter.cs
  src/Presentation/Presenters/GuestPresenter.cs
  src/Presentation/Views/DetallesReservaView.cs
  src/Presentation/Views/GuestView.Designer.cs
  src/Presentation/Views/GuestView.cs
  src/Presentation/Views/GuestView.resx
  src/Presentation/Views/IDetallesReservaView.cs
  src/Presentation/Views/IGuestView.cs
  src/Services/Services/HabitacionServices.cs
  src/Services/Services/IHabitacionServices.cs
  src/Services/Services/IReservaService.cs
  src/Services/Services/ReservaService.cs
Labels: enhancement

#68 añade boton modificar reservas y metodo para traer reservas activas
  src/Domain/Entities/Reserva/Reserva.cs
  src/Domain/Interfaces/IReservaRepository.cs
  src/Infraestructure/DataAccess/Repositories/ReservaRepository.cs
  src/Presentation/Presenters/GuestPresenter.cs
  src/Presentation/Presenters/LoginPresenter.cs
  src/Presentation/Utils/INavigationService.cs
  src/Presentation/Utils/IPresenter.cs
  src/Presentation/Utils/NavigationService.cs
  src/Presentation/Views/GuestView.Designer.cs
  src/Presentation/Views/GuestView.cs
  src/Presentation/Views/GuestView.resx
  src/Presentation/Views/IGuestView.cs
  src/Services/Services/HabitacionServices.cs
  src/Services/Services/IReservaService.cs
  src/Services/Services/ReservaService.cs
Labels: enhancement

#69 Dashboard
  src/Domain/Entities/Usuario/IUsuario.cs
  src/Domain/Entities/Usuario/Usuario.cs
  src/Infraestructure/DataAccess/Repositories/ReservaRepository.cs
  src/Presentation/Presenters/AdminPresenter.cs
  src/Presentation/Presenters/IAdminPresenter.cs
  src/Presentation/Presenters/LoginPresenter.cs
  src/Presentation/Program.cs
  src/Presentation/Views/AdminView.Designer.cs
  src/Presentation/Views/AdminView.cs
  src/Presentation/Views/AdminView.resx
  src/Presentation/Views/GuestView.cs
  src/Presentation/Views/GuestView.resx
  src/Presentation/Views/IAdminView.cs
Labels: enhancement

#73 Funcionalidad de cierre de la app
  src/Presentation/Presenters/AdminPresenter.cs
  src/Presentation/Presenters/GuestPresenter.cs
  src/Presentation/Views/AdminView.cs
  src/Presentation/Views/BaseView.cs
  src/Presentation/Views/CambiarContraseñaForm.cs
  src/Presentation/Views/CrearEditarHabitacionView.cs
  src/Presentation/Views/DetallesReservaView.cs
  src/Presentation/Views/GuestView.Designer.cs
  src/Presentation/Views/GuestView.cs
  src/Presentation/Views/GuestView.resx
  src/Presentation/Views/IAdminView.cs
  src/Presentation/Views/IGuestView.cs
  src/Presentation/Views/LoginView.cs
  src/Presentation/Views/RegisterView.cs
Labels: enhancement
